# Используем официальный Python-образ
FROM python:3.12-slim

# Устанавливаем рабочую директорию внутри контейнера
WORKDIR /app

# Копируем файлы с зависимостями в контейнер
COPY requirements.txt .

# Устанавливаем зависимости
RUN pip3 install --no-cache-dir -r requirements.txt

# Копируем весь код приложения в контейнер
COPY . .

# Открываем порт 8501 (по умолчанию Streamlit 8501)
EXPOSE 8501

# Запускаем Streamlit-приложение
CMD ["streamlit", "run", "st_project.py", "--server.port=8501", "--server.address=0.0.0.0"]
